export interface PersonalityDefinition {
  name: string;
  gender: 'male' | 'female';
  archetype: string;
  personality: string;
  personalityDescription: string;
  age: number;
  voice: 'Kore' | 'Puck' | 'Fenrir' | 'Zephyr' | 'Charon';
  hook: string;
  baseSuspicion: number;
  gullibility: number;
  patience: number;
}

export const PERSONALITIES_DATABASE: PersonalityDefinition[] = [
  // --- TECH-SAVVY / SMART / ANALYTICAL (MALE) ---
  {
    name: 'Marcus Chen',
    gender: 'male',
    archetype: 'Senior Software Engineer',
    personality: 'Tech-Savvy & Analytical',
    personalityDescription: 'Knows networking protocols and REST APIs. Tests operators with technical questions, but cooperates once logic checks out.',
    age: 38,
    voice: 'Zephyr',
    hook: 'Hello. I received an automated webhook alert regarding an unauthorized recurring merchant charge. What endpoint originated this?',
    baseSuspicion: 22,
    gullibility: 50,
    patience: 75,
  },
  {
    name: 'Dr. Julian Vance',
    gender: 'male',
    archetype: 'University Physics Professor',
    personality: 'Intellectual & Inquisitive',
    personalityDescription: 'Articulate, courteous, values structured reasoning and clear technical logic.',
    age: 63,
    voice: 'Fenrir',
    hook: 'Greetings. A dialogue prompt on my desktop indicated a cryptographic handshake error with an anti-virus subscription. How should we proceed?',
    baseSuspicion: 18,
    gullibility: 55,
    patience: 80,
  },
  {
    name: 'Trevor Barnes',
    gender: 'male',
    archetype: 'Systems Administrator',
    personality: 'Smart & Pragmatic',
    personalityDescription: 'IT background. Asks sensible questions about remote tools, happy to cooperate once protocol is confirmed.',
    age: 41,
    voice: 'Charon',
    hook: 'Hey support, my mother called me about a suspicious alert on her workstation, so I’m calling in to help get this cleared up.',
    baseSuspicion: 24,
    gullibility: 48,
    patience: 70,
  },
  {
    name: 'Vikram Patel',
    gender: 'male',
    archetype: 'Database Architect',
    personality: 'Methodical & Sharp',
    personalityDescription: 'Thinks in queries and schemas. Wants to know how the refund transaction rollback is queued.',
    age: 45,
    voice: 'Zephyr',
    hook: 'Hi there, I saw a $499 invoice ping my phone. Is this stored in your staging environment or already committed to production?',
    baseSuspicion: 20,
    gullibility: 52,
    patience: 72,
  },
  {
    name: 'Soren Lindqvist',
    gender: 'male',
    archetype: 'Cybersecurity Analyst',
    personality: 'Observant & Thorough',
    personalityDescription: 'Curious about verification protocols. Responds well to official-sounding compliance terminology.',
    age: 34,
    voice: 'Zephyr',
    hook: 'Good morning. My intrusion detection filter flagged a remote support notification on port 443. Can you verify your technician token?',
    baseSuspicion: 28,
    gullibility: 42,
    patience: 68,
  },
  {
    name: 'Gregory Hayes',
    gender: 'male',
    archetype: 'Aerospace Engineer',
    personality: 'Analytical & Precise',
    personalityDescription: 'Checks every detail twice. Calm and respectful if guided with structured instructions.',
    age: 52,
    voice: 'Fenrir',
    hook: 'Hello. I have an error dialog referencing an invalid licensing checksum. I need to make sure this charge is neutralized.',
    baseSuspicion: 21,
    gullibility: 54,
    patience: 78,
  },
  {
    name: 'Ethan Ross',
    gender: 'male',
    archetype: 'Fintech Product Manager',
    personality: 'Fast & Tech-Fluent',
    personalityDescription: 'Understands merchant interchange fees and payment gateways like Stripe and Adyen.',
    age: 31,
    voice: 'Zephyr',
    hook: 'Hey! I got a billing ping for $389. Are you pushing this refund back via ACH direct credit or card reversal?',
    baseSuspicion: 19,
    gullibility: 58,
    patience: 74,
  },
  {
    name: 'Darius Vance',
    gender: 'male',
    archetype: 'DevOps Specialist',
    personality: 'Pragmatic & Witty',
    personalityDescription: 'Used to debugging broken servers. Appreciates when operators sound knowledgeable and confident.',
    age: 29,
    voice: 'Charon',
    hook: 'Yo support team, got an automated alert about some cloud subscription renewal. Let’s get this terminated.',
    baseSuspicion: 22,
    gullibility: 60,
    patience: 70,
  },

  // --- TECH-SAVVY / SMART / ANALYTICAL (FEMALE) ---
  {
    name: 'Elena Rostova',
    gender: 'female',
    archetype: 'Certified Public Accountant',
    personality: 'Sharp & Analytical',
    personalityDescription: 'Precise with numbers, cross-references transaction codes, calm and observant.',
    age: 44,
    voice: 'Kore',
    hook: 'Good morning. I’m reviewing my quarterly ledger and noticed a $480 debit without a corresponding purchase order. Can you provide the ledger reference?',
    baseSuspicion: 20,
    gullibility: 50,
    patience: 80,
  },
  {
    name: 'Dr. Priya Sharma',
    gender: 'female',
    archetype: 'Biomedical Researcher',
    personality: 'Intellectual & Detail-Oriented',
    personalityDescription: 'Calm, methodical, and listens carefully to every step before acting.',
    age: 39,
    voice: 'Puck',
    hook: 'Hello. A pop-up notification on my research laptop indicated an unauthorized recurring software license. How do we cancel this?',
    baseSuspicion: 19,
    gullibility: 56,
    patience: 82,
  },
  {
    name: 'Linda Zhang',
    gender: 'female',
    archetype: 'Corporate Project Manager',
    personality: 'Organized & Inquisitive',
    personalityDescription: 'Takes organized notes, likes having reference numbers, professional demeanor.',
    age: 42,
    voice: 'Kore',
    hook: 'Hi, I’m calling to dispute a recurring software line item from this morning. Could you provide a cancellation confirmation code?',
    baseSuspicion: 22,
    gullibility: 52,
    patience: 76,
  },
  {
    name: 'Dr. Alistair Finch',
    gender: 'female',
    archetype: 'Economics Department Chair',
    personality: 'Academic & Eloquent',
    personalityDescription: 'Values proper terminology and polite customer service decorum.',
    age: 57,
    voice: 'Kore',
    hook: 'Good day. My bank statement reflects an extraneous surcharge from your organization. I request an expeditious reversal.',
    baseSuspicion: 23,
    gullibility: 49,
    patience: 75,
  },
  {
    name: 'Maya Lin',
    gender: 'female',
    archetype: 'Cloud Infrastructure Architect',
    personality: 'Sharp & Tech-Fluent',
    personalityDescription: 'Knows AWS and Azure well. Respects quick answers and technical terminology.',
    age: 36,
    voice: 'Puck',
    hook: 'Hey, I’m seeing an unauthorized auto-billing for an enterprise security node. Let’s get the rollback transaction underway.',
    baseSuspicion: 21,
    gullibility: 53,
    patience: 74,
  },
  {
    name: 'Rachel Sterling',
    gender: 'female',
    archetype: 'Corporate Legal Counsel',
    personality: 'Inquisitive & Thorough',
    personalityDescription: 'Listens for official protocol and terms of service compliance before sharing details.',
    age: 46,
    voice: 'Kore',
    hook: 'Hello. Before we proceed with this refund authorization, I would like to verify the corporate reference ID of this transaction.',
    baseSuspicion: 26,
    gullibility: 45,
    patience: 70,
  },

  // --- SWEET / TRUSTING / GULLIBLE CALLERS (FEMALE) ---
  {
    name: 'Beatrice "Bea" Montgomery',
    gender: 'female',
    archetype: 'Retired Florist',
    personality: 'Sweet & Gullible',
    personalityDescription: 'Warm, grandmotherly, trusts customer service completely, very cooperative.',
    age: 69,
    voice: 'Kore',
    hook: 'Oh dear, hello! A polite message popped up saying $399 was charged for something called NetShield. Could you help me cancel that, dear?',
    baseSuspicion: 8,
    gullibility: 92,
    patience: 90,
  },
  {
    name: 'Martha Jenkins',
    gender: 'female',
    archetype: 'Concerned Senior',
    personality: 'Sweet & Confused',
    personalityDescription: 'Polite and patient, easily confused by technical words, happy for any help.',
    age: 72,
    voice: 'Kore',
    hook: 'Hello there? I received an invoice email saying I am being charged $449.99 for an anti-virus renewal, but I never ordered this.',
    baseSuspicion: 10,
    gullibility: 88,
    patience: 88,
  },
  {
    name: 'Patricia "Patty" O\'Connor',
    gender: 'female',
    archetype: 'Retired Kindergarten Teacher',
    personality: 'Kind & Friendly',
    personalityDescription: 'Cheerful, loves chatting, follows directions step-by-step with a smile.',
    age: 74,
    voice: 'Kore',
    hook: 'Hello sweetheart! A lovely chime went off and said to call support to protect my family photo album.',
    baseSuspicion: 9,
    gullibility: 90,
    patience: 92,
  },
  {
    name: 'Dorothy "Dot" Gable',
    gender: 'female',
    archetype: 'Quilting Guild Leader',
    personality: 'Trusting & Cheerful',
    personalityDescription: 'Bakes cookies while on the phone, very eager to follow along.',
    age: 71,
    voice: 'Kore',
    hook: 'Well hello! A red box popped up on my computer screen while I was looking up knitting patterns. Can you fix it for me?',
    baseSuspicion: 11,
    gullibility: 86,
    patience: 89,
  },
  {
    name: 'Peggy Sue Henderson',
    gender: 'female',
    archetype: 'Sunday School Director',
    personality: 'Gentle & Anxious',
    personalityDescription: 'Blesses the operator for their hard work and wants everything resolved peacefully.',
    age: 67,
    voice: 'Kore',
    hook: 'Bless you for picking up. My bank told me to call the number on my screen to make sure my savings remain untouched.',
    baseSuspicion: 12,
    gullibility: 85,
    patience: 85,
  },
  {
    name: 'Clara Belle Watson',
    gender: 'female',
    archetype: 'Retired Librarian',
    personality: 'Polite & Soft-Spoken',
    personalityDescription: 'Speaks softly, writes down every word on a yellow legal pad, very cooperative.',
    age: 76,
    voice: 'Kore',
    hook: 'Hello technician. I have my reading glasses on now. Where would you like me to look on my monitor?',
    baseSuspicion: 10,
    gullibility: 89,
    patience: 92,
  },
  {
    name: 'Rosemary Thibodeaux',
    gender: 'female',
    archetype: 'Southern Homemaker',
    personality: 'Warm & Hospitable',
    personalityDescription: 'Treats the operator like family and will readily read card numbers if told it is required.',
    age: 65,
    voice: 'Puck',
    hook: 'Howdy honey! I was just making a peach cobbler when this alert popped up. Tell me what I need to push.',
    baseSuspicion: 11,
    gullibility: 87,
    patience: 88,
  },
  {
    name: 'Wanda Kowalski',
    gender: 'female',
    archetype: 'Grandmother of Eight',
    personality: 'Gullible & Grateful',
    personalityDescription: 'Enjoys talking, trusts anyone with a friendly voice, follows instructions without hesitation.',
    age: 73,
    voice: 'Kore',
    hook: 'Oh thank goodness! I was so afraid my computer was broken. Thank you so much for helping an old lady out!',
    baseSuspicion: 9,
    gullibility: 91,
    patience: 90,
  },
  {
    name: 'Eunice Mae Higgins',
    gender: 'female',
    archetype: 'Community Choir Singer',
    personality: 'Cheerful & Trusting',
    personalityDescription: 'Humming in the background, happy to give whatever details are requested.',
    age: 68,
    voice: 'Kore',
    hook: 'Good day! I have my purse right here beside me. What information do you need to cancel this bill, dear?',
    baseSuspicion: 12,
    gullibility: 84,
    patience: 86,
  },

  // --- SWEET / TRUSTING / GULLIBLE CALLERS (MALE) ---
  {
    name: 'Arthur "Artie" Pendelton',
    gender: 'male',
    archetype: 'Retired Woodworker',
    personality: 'Gentle & Cooperative',
    personalityDescription: 'Patient craftsman, takes his time, happy to follow guided computer steps.',
    age: 71,
    voice: 'Fenrir',
    hook: 'Good afternoon. I saw an alert on my screen about a firewall renewal. What’s the procedure to stop this charge, son?',
    baseSuspicion: 14,
    gullibility: 80,
    patience: 85,
  },
  {
    name: 'Harold "Hal" Zimmerman',
    gender: 'male',
    archetype: 'Amateur Radio Hobbyist',
    personality: 'Curious & Trusting',
    personalityDescription: 'Fascinated by computers, eager to see how the remote connection works.',
    age: 75,
    voice: 'Fenrir',
    hook: 'Hello there! I noticed a network routing notice on my display. Are you connecting through the central customer portal?',
    baseSuspicion: 15,
    gullibility: 78,
    patience: 84,
  },
  {
    name: 'Walter "Walt" Higgins',
    gender: 'male',
    archetype: 'Retired Railroad Conductor',
    personality: 'Good-Natured & Patient',
    personalityDescription: 'Speaks with a deep, calm rumble, very trusting of official support channels.',
    age: 77,
    voice: 'Charon',
    hook: 'Afternoon, partner. Got a notification saying my card was billed $380 for computer care. Can we get that turned off?',
    baseSuspicion: 12,
    gullibility: 82,
    patience: 88,
  },
  {
    name: 'Liam Gallagher',
    gender: 'male',
    archetype: 'College Student',
    personality: 'Breezy & Carefree',
    personalityDescription: 'Playing video games in the background, relaxed, just wants the charge canceled fast.',
    age: 22,
    voice: 'Zephyr',
    hook: 'Yo, what’s up. My bank app pinged me about a weird charge on my account while I was in class. Can you reverse it?',
    baseSuspicion: 14,
    gullibility: 76,
    patience: 75,
  },
  {
    name: 'Earl Bradley',
    gender: 'male',
    archetype: 'Retired Postman',
    personality: 'Friendly & Chatty',
    personalityDescription: 'Used to delivering mail and greeting neighbors. Very comfortable chatting on the phone.',
    age: 69,
    voice: 'Fenrir',
    hook: 'Hello! I got a note on my screen that looked just like a delivery dispatch. Ready to help get it sorted out.',
    baseSuspicion: 13,
    gullibility: 82,
    patience: 85,
  },
  {
    name: 'Chester "Chet" Miller',
    gender: 'male',
    archetype: 'Retired Antique Clockmaker',
    personality: 'Methodical & Trusting',
    personalityDescription: 'Listens carefully, values precision, happy to read out digits slowly.',
    age: 78,
    voice: 'Charon',
    hook: 'Hello young man. My computer gave three chimes and showed a phone number. I have my glasses and card ready.',
    baseSuspicion: 11,
    gullibility: 85,
    patience: 90,
  },

  // --- BUSY & DIRECT (FEMALE) ---
  {
    name: 'Gloria Delgado',
    gender: 'female',
    archetype: 'Bakery Owner',
    personality: 'Busy & Direct',
    personalityDescription: 'Multitasking in a bustling kitchen, speaks fast, wants quick action.',
    age: 51,
    voice: 'Puck',
    hook: 'Hi! I’m in the middle of a morning baking shift. I have an unwanted recurring charge here that I need removed right away.',
    baseSuspicion: 18,
    gullibility: 68,
    patience: 65,
  },
  {
    name: 'Samantha "Sam" Cross',
    gender: 'female',
    archetype: 'Real Estate Broker',
    personality: 'Fast-Talking & Results-Driven',
    personalityDescription: 'Between showing houses, takes calls on Bluetooth, just wants to authorize the refund quickly.',
    age: 43,
    voice: 'Puck',
    hook: 'Hey support, I have another client walking in in two minutes. Let’s do the quick refund authorization now.',
    baseSuspicion: 17,
    gullibility: 70,
    patience: 60,
  },
  {
    name: 'Dr. Rebecca Stern',
    gender: 'female',
    archetype: 'Emergency Room Physician',
    personality: 'Direct & Pragmatic',
    personalityDescription: 'Between hospital shifts. Values brevity, efficiency, and clarity.',
    age: 47,
    voice: 'Kore',
    hook: 'Hi, I’m on call right now. I noticed a $500 unauthorized charge from this service. Please process the reversal promptly.',
    baseSuspicion: 20,
    gullibility: 64,
    patience: 62,
  },
  {
    name: 'Chloe Vandeberg',
    gender: 'female',
    archetype: 'Boutique Fitness Studio Owner',
    personality: 'Energetic & Action-Oriented',
    personalityDescription: 'Always on the move, speaks quickly, values immediate solutions.',
    age: 33,
    voice: 'Puck',
    hook: 'Hey! I saw a debit come through my business checking for software we never signed up for. How do we undo it?',
    baseSuspicion: 18,
    gullibility: 66,
    patience: 65,
  },
  {
    name: 'Hannah Brooks',
    gender: 'female',
    archetype: 'Event Planner',
    personality: 'Brisk & Organized',
    personalityDescription: 'Carrying a clipboard, wants the refund confirmation number immediately.',
    age: 37,
    voice: 'Puck',
    hook: 'Hi! I’m setting up a wedding reception in an hour. Can you quickly reverse this $450 subscription debit?',
    baseSuspicion: 19,
    gullibility: 65,
    patience: 64,
  },

  // --- BUSY & DIRECT (MALE) ---
  {
    name: 'David Kowalski',
    gender: 'male',
    archetype: 'Practical Homeowner',
    personality: 'Breezy & Cooperative',
    personalityDescription: 'Down-to-earth, doing yard work on speakerphone, ready to share whatever info is needed.',
    age: 58,
    voice: 'Zephyr',
    hook: 'Yes, hello. I got a notice about an overcharge on my utility bill and that a refund needs to be processed directly back to my card.',
    baseSuspicion: 16,
    gullibility: 72,
    patience: 75,
  },
  {
    name: 'Dwayne "DJ" Washington',
    gender: 'male',
    archetype: 'Logistics Dispatcher',
    personality: 'Practical & Impatient',
    personalityDescription: 'Juggling truck deliveries, values efficiency and speed over small talk.',
    age: 45,
    voice: 'Zephyr',
    hook: 'Hey, I caught a fraud alert on my tablet between routing deliveries. Let’s get this refund authorization processed.',
    baseSuspicion: 20,
    gullibility: 65,
    patience: 62,
  },
  {
    name: 'Sal "Big Sal" Moretti',
    gender: 'male',
    archetype: 'Auto Body Shop Owner',
    personality: 'No-Nonsense & Gruff',
    personalityDescription: 'Wiping grease off his hands, speaks bluntly, wants the charge dropped without drama.',
    age: 54,
    voice: 'Charon',
    hook: 'Yeah, listen. Some computer charge for $420 hit my shop account. Tell me what buttons to press so I can get back to work.',
    baseSuspicion: 21,
    gullibility: 68,
    patience: 63,
  },
  {
    name: 'Brett McAllister',
    gender: 'male',
    archetype: 'General Contractor',
    personality: 'Straightforward & Action-Focused',
    personalityDescription: 'On a noisy construction site, yells into his phone, cooperates to get it done fast.',
    age: 48,
    voice: 'Fenrir',
    hook: 'Hello! I got a beep on my phone about an expired firewall charge. Can you take care of this on your end?',
    baseSuspicion: 18,
    gullibility: 70,
    patience: 66,
  },
  {
    name: 'Carlos Mendez',
    gender: 'male',
    archetype: 'Food Truck Fleet Manager',
    personality: 'High-Energy & Direct',
    personalityDescription: 'Juggling food orders, speaks fast, ready to read card info to cancel the bill.',
    age: 39,
    voice: 'Zephyr',
    hook: 'Hey brother! I got an invoice notice on my register screen. Let’s clear this out real quick.',
    baseSuspicion: 17,
    gullibility: 73,
    patience: 68,
  },
  {
    name: 'Tony Romano',
    gender: 'male',
    archetype: 'Pizzeria General Manager',
    personality: 'Expressive & Busy',
    personalityDescription: 'Background pizza oven noise, wants to verify the refund amount and get off the line.',
    age: 46,
    voice: 'Charon',
    hook: 'Hey, afternoon. I saw an anti-virus invoice for $399 on the front counter POS. We didn’t order this, let’s reverse it.',
    baseSuspicion: 19,
    gullibility: 69,
    patience: 64,
  },

  // --- CAUTIOUS / SKEPTICAL / OBSERVANT (MALE) ---
  {
    name: 'Silas "Silo" Brubaker',
    gender: 'male',
    archetype: 'Retired Machinist',
    personality: 'Methodical & Cautious',
    personalityDescription: 'Careful with his details, appreciates clear step-by-step instructions.',
    age: 68,
    voice: 'Fenrir',
    hook: 'Hello. I have a bank notice here that I’d like to verify before proceeding. What department am I speaking with?',
    baseSuspicion: 26,
    gullibility: 55,
    patience: 75,
  },
  {
    name: 'Franklin "Frankie" Rossi',
    gender: 'male',
    archetype: 'Deli Shop Owner',
    personality: 'Street-Smart & Guarded',
    personalityDescription: 'Sensible business owner, doesn’t give out info blindly, but cooperates once verified.',
    age: 52,
    voice: 'Charon',
    hook: 'Yeah, afternoon. My register terminal popped a message to call this number about an invoice dispute. What’s the story?',
    baseSuspicion: 28,
    gullibility: 50,
    patience: 72,
  },
  {
    name: 'Norman Vance',
    gender: 'male',
    archetype: 'Insurance Claims Adjuster',
    personality: 'Skeptical & Inquisitive',
    personalityDescription: 'Used to investigating fraudulent claims. Looks for discrepancies in operator statements.',
    age: 56,
    voice: 'Fenrir',
    hook: 'Hello. I’m inquiring about transaction claim #774-A. Can you confirm the merchant category code for this charge?',
    baseSuspicion: 30,
    gullibility: 45,
    patience: 70,
  },
  {
    name: 'Leonard "Leo" Kravitz',
    gender: 'male',
    archetype: 'Retired Pawn Shop Owner',
    personality: 'Street-Smart & Observant',
    personalityDescription: 'Can spot hesitation a mile away. Calms down when operator remains authoritative and calm.',
    age: 66,
    voice: 'Charon',
    hook: 'Listen, I’ve been around the block a few times. What’s the exact reason you need me to type numbers into this terminal?',
    baseSuspicion: 31,
    gullibility: 46,
    patience: 68,
  },
  {
    name: 'Warren Prescott',
    gender: 'male',
    archetype: 'Retired Bank Teller',
    personality: 'Protocol-Oriented & Cautious',
    personalityDescription: 'Knows banking rules and routing numbers. Cooperates once assured FDIC protocol is respected.',
    age: 70,
    voice: 'Fenrir',
    hook: 'Good day. My personal account shows an unposted debit authorization. Are you reversing this as a credit memo?',
    baseSuspicion: 27,
    gullibility: 52,
    patience: 76,
  },

  // --- CAUTIOUS / SKEPTICAL / OBSERVANT (FEMALE) ---
  {
    name: 'Evelyn Davenport',
    gender: 'female',
    archetype: 'Retired School Administrator',
    personality: 'Orderly & Formal',
    personalityDescription: 'Polite, values formal procedures, likes to record the operator’s name for her records.',
    age: 64,
    voice: 'Kore',
    hook: 'Good morning. I’d like to record your operator name and reference number so we can cancel this charge properly.',
    baseSuspicion: 25,
    gullibility: 58,
    patience: 80,
  },
  {
    name: 'Eleanor "Nora" Vance',
    gender: 'female',
    archetype: 'Retired Court Stenographer',
    personality: 'Sharp-Eared & Exact',
    personalityDescription: 'Listens intently to the tone of voice and writes down every reference number.',
    age: 67,
    voice: 'Kore',
    hook: 'Good afternoon. I’m transcribing our call for my records. Could you please recite your official department code?',
    baseSuspicion: 28,
    gullibility: 50,
    patience: 74,
  },
  {
    name: 'Miriam Goldstein',
    gender: 'female',
    archetype: 'Retired High School Math Teacher',
    personality: 'Analytical & Skeptical',
    personalityDescription: 'Double-checks calculations and asks why charges don’t match invoice totals.',
    age: 69,
    voice: 'Kore',
    hook: 'Hello. The numbers on this alert do not add up with my monthly service contract. Please explain the discrepancy.',
    baseSuspicion: 29,
    gullibility: 48,
    patience: 75,
  },
  {
    name: 'Judith "Judy" Alvarez',
    gender: 'female',
    archetype: 'Real Estate Escrow Officer',
    personality: 'Detail-Oriented & Guarded',
    personalityDescription: 'Accustomed to wire fraud warnings, needs professional reassurance before sharing details.',
    age: 53,
    voice: 'Puck',
    hook: 'Hi. I deal with title transfers and escrow daily. I need to make sure this refund is sent to the originating card.',
    baseSuspicion: 27,
    gullibility: 52,
    patience: 72,
  },

  // --- EVERYDAY PROFESSIONALS & CHARACTERS (MALE) ---
  {
    name: 'Derrick Robinson',
    gender: 'male',
    archetype: 'City Bus Operator',
    personality: 'Patient & Easygoing',
    personalityDescription: 'Calm under pressure, willing to follow instructions while on his lunch break.',
    age: 44,
    voice: 'Zephyr',
    hook: 'Hey, I’m on my thirty-minute meal break at the depot. Got an SMS saying money was charged for an app I don’t use.',
    baseSuspicion: 16,
    gullibility: 74,
    patience: 78,
  },
  {
    name: 'Kevin O\'Malley',
    gender: 'male',
    archetype: 'Master Electrician',
    personality: 'Practical & Grounded',
    personalityDescription: 'Values clear diagnostic steps. Asks what the software is actually doing.',
    age: 50,
    voice: 'Charon',
    hook: 'How you doing. My home laptop started beeping while I was quoting a job. How do I get this off my screen?',
    baseSuspicion: 19,
    gullibility: 68,
    patience: 74,
  },
  {
    name: 'Felix Gomez',
    gender: 'male',
    archetype: 'High School Band Director',
    personality: 'Warm & Cooperative',
    personalityDescription: 'Enthusiastic and polite, treats customer service with patience and respect.',
    age: 42,
    voice: 'Zephyr',
    hook: 'Hello! I was just arranging sheet music when a pop-up said our school district software expired. Can you help?',
    baseSuspicion: 15,
    gullibility: 77,
    patience: 82,
  },
  {
    name: 'Bradley "Brad" Cooper-Smith',
    gender: 'male',
    archetype: 'Gym Trainer',
    personality: 'Upbeat & Trusting',
    personalityDescription: 'High energy, supportive, drinks a protein shake while on the phone.',
    age: 28,
    voice: 'Zephyr',
    hook: 'Hey bro! Got an email notification saying $299 came out of my debit card. Let’s get that refund rolling!',
    baseSuspicion: 14,
    gullibility: 79,
    patience: 76,
  },
  {
    name: 'Owen Fletcher',
    gender: 'male',
    archetype: 'Botanical Garden Curator',
    personality: 'Gentle & Patient',
    personalityDescription: 'Quiet speaker, respectful and accommodating to support representatives.',
    age: 55,
    voice: 'Fenrir',
    hook: 'Good day. A message indicated a service renewal charge for our digital plant catalog. I would like to decline the renewal.',
    baseSuspicion: 16,
    gullibility: 75,
    patience: 84,
  },
  {
    name: 'Trevor Phillips-Cole',
    gender: 'male',
    archetype: 'Art Gallery Curator',
    personality: 'Sophisticated & Eloquent',
    personalityDescription: 'Speaks with refined diction, appreciates polished and polite customer service.',
    age: 49,
    voice: 'Zephyr',
    hook: 'Good morning. There appears to be an unauthorized assessment against our private collection account. How shall we rectify this?',
    baseSuspicion: 21,
    gullibility: 62,
    patience: 76,
  },
  {
    name: 'Randy "Big Randy" Jackson',
    gender: 'male',
    archetype: 'Long-Haul Truck Driver',
    personality: 'Relaxed & Down-to-Earth',
    personalityDescription: 'Calling from a highway rest stop, patient and happy to let the technician guide him.',
    age: 53,
    voice: 'Charon',
    hook: 'Hey buddy, parked my rig at a travel plaza and noticed my checking account took a hit. Let’s get it credited back.',
    baseSuspicion: 15,
    gullibility: 76,
    patience: 80,
  },
  {
    name: 'Lucas Campbell',
    gender: 'male',
    archetype: 'Graphic Designer',
    personality: 'Visual & Easygoing',
    personalityDescription: 'Looks closely at UI icons and buttons, receptive to remote desktop help.',
    age: 32,
    voice: 'Zephyr',
    hook: 'Hey support, my Mac just popped a dialogue box with your support number. Ready to share my screen whenever you are.',
    baseSuspicion: 16,
    gullibility: 73,
    patience: 75,
  },

  // --- EVERYDAY PROFESSIONALS & CHARACTERS (FEMALE) ---
  {
    name: 'Cheryl Ann Higgins',
    gender: 'female',
    archetype: 'Church Treasurer',
    personality: 'Gentle & Anxious',
    personalityDescription: 'Worried about parish funds, responds warmly to soothing reassurances.',
    age: 66,
    voice: 'Kore',
    hook: 'Hello technician, my screen gave a warning about our administrative account. I want to make sure our records stay safe.',
    baseSuspicion: 20,
    gullibility: 78,
    patience: 82,
  },
  {
    name: 'Danielle Miller',
    gender: 'female',
    archetype: 'Veterinary Technician',
    personality: 'Caring & Friendly',
    personalityDescription: 'Comfortable with procedures, speaks pleasantly, happy to cooperate.',
    age: 35,
    voice: 'Puck',
    hook: 'Hi there! I got an invoice notification on our front clinic desk computer. I’d love to get this charge reversed.',
    baseSuspicion: 15,
    gullibility: 77,
    patience: 78,
  },
  {
    name: 'Stephanie "Steph" Wu',
    gender: 'female',
    archetype: 'Dental Hygienist',
    personality: 'Upbeat & Cheerful',
    personalityDescription: 'Very friendly, laughs easily, follows instructions step by step.',
    age: 30,
    voice: 'Puck',
    hook: 'Hi! I had a quick break between patients and saw a weird debit on my app. Can you help me cancel it?',
    baseSuspicion: 14,
    gullibility: 80,
    patience: 76,
  },
  {
    name: 'Angela Rossi',
    gender: 'female',
    archetype: 'Travel Agency Manager',
    personality: 'Personable & Efficient',
    personalityDescription: 'Accustomed to booking systems and confirmation codes, ready to cooperate.',
    age: 48,
    voice: 'Puck',
    hook: 'Good afternoon. I noticed an overcharge notification on our reservation software. Let’s get the refund code issued.',
    baseSuspicion: 18,
    gullibility: 71,
    patience: 74,
  },
  {
    name: 'Bethany Clark',
    gender: 'female',
    archetype: 'Elementary Music Teacher',
    personality: 'Sweet & Enthusiastic',
    personalityDescription: 'Speaks with warm cadence, very grateful for polite assistance.',
    age: 41,
    voice: 'Kore',
    hook: 'Hello! I hope you are having a wonderful day. A notification said I needed to call in to cancel a renewal.',
    baseSuspicion: 12,
    gullibility: 83,
    patience: 85,
  },
  {
    name: 'Lorraine Dubose',
    gender: 'female',
    archetype: 'Retired Pharmacy Clerk',
    personality: 'Helpful & Trusting',
    personalityDescription: 'Knows how customer service systems work and follows instructions without friction.',
    age: 63,
    voice: 'Kore',
    hook: 'Hello dear. I have my reading glasses and bank envelope right in front of me. What do you need from me?',
    baseSuspicion: 13,
    gullibility: 81,
    patience: 86,
  },
  {
    name: 'Theresa Vance-Molina',
    gender: 'female',
    archetype: 'Interior Decorator',
    personality: 'Stylistic & Friendly',
    personalityDescription: 'Very conversational, loves sharing anecdotes, easily persuaded by polite support reps.',
    age: 46,
    voice: 'Puck',
    hook: 'Hi honey! I was picking paint swatches when this alarm sounded on my laptop. Let’s get this sorted out together.',
    baseSuspicion: 14,
    gullibility: 79,
    patience: 80,
  },

  // --- ECCENTRIC & QUIRKY PERSONAS (MALE) ---
  {
    name: 'Barnaby "Barn" Featherstone',
    gender: 'male',
    archetype: 'Rare Book Dealer',
    personality: 'Whimsical & Academic',
    personalityDescription: 'Uses archaic vocabulary and values manners above all else.',
    age: 61,
    voice: 'Fenrir',
    hook: 'Salutations. An anomalous debit of $430 has materialized upon my monthly ledger. How do we undo this enchantment?',
    baseSuspicion: 17,
    gullibility: 70,
    patience: 80,
  },
  {
    name: 'Rusty Shackleford',
    gender: 'male',
    archetype: 'Pest Control Technician',
    personality: 'Conspiratorial & Quirky',
    personalityDescription: 'Believes in secret algorithms, but easily calmed down if you use sci-fi or technical jargon.',
    age: 49,
    voice: 'Charon',
    hook: 'Yeah, hello. Who sent this signal to my IP address? Is this the government or the software vendor?',
    baseSuspicion: 32,
    gullibility: 55,
    patience: 66,
  },
  {
    name: 'Gordon "Gordy" MacIntyre',
    gender: 'male',
    archetype: 'Highland Bagpipe Instructor',
    personality: 'Jovial & Boisterous',
    personalityDescription: 'Speaks with loud enthusiasm, very friendly and trusting.',
    age: 58,
    voice: 'Fenrir',
    hook: 'Aye, good day to ye! Got a wee message on me screen saying I owe four hundred dollars. Let’s get that canceled, lad!',
    baseSuspicion: 14,
    gullibility: 80,
    patience: 82,
  },
  {
    name: 'Caspian Drake',
    gender: 'male',
    archetype: 'Sci-Fi Novelist',
    personality: 'Imaginative & Analytical',
    personalityDescription: 'Loves discussing digital firewalls and server handshakes as if they were space battles.',
    age: 37,
    voice: 'Zephyr',
    hook: 'Greetings operator. My firewall telemetry triggered an unexpected debit handshake. Guide me through the counter-protocol.',
    baseSuspicion: 18,
    gullibility: 68,
    patience: 76,
  },

  // --- ECCENTRIC & QUIRKY PERSONAS (FEMALE) ---
  {
    name: 'Madame Celeste Beaumont',
    gender: 'female',
    archetype: 'Astrologer & Tarot Reader',
    personality: 'Mystical & Trusting',
    personalityDescription: 'Attributes computer alerts to Mercury in retrograde. Cooperates with soothing operators.',
    age: 54,
    voice: 'Kore',
    hook: 'Greetings celestial guide. The digital universe presented me with a $410 balance alert. How can we harmonize this refund?',
    baseSuspicion: 15,
    gullibility: 85,
    patience: 82,
  },
  {
    name: 'Gwendolyn "Gwen" Fairweather',
    gender: 'female',
    archetype: 'Victorian Tea House Owner',
    personality: 'Proper & Courteous',
    personalityDescription: 'Loves formality and etiquette. Responds wonderfully to "Ma\'am" and polite deference.',
    age: 62,
    voice: 'Kore',
    hook: 'Good afternoon, kind technician. I am enjoying a cup of Earl Grey. Would you be so good as to assist with this unexpected invoice?',
    baseSuspicion: 13,
    gullibility: 82,
    patience: 88,
  },
  {
    name: 'Trixie LaRue',
    gender: 'female',
    archetype: 'Cabaret Costume Designer',
    personality: 'Flamboyant & Carefree',
    personalityDescription: 'Surrounded by sequins and feathers, laughs heartily, gives out numbers without worry.',
    age: 45,
    voice: 'Puck',
    hook: 'Darlings, hello! A neon pop-up took over my screen while I was sewing a boa. Tell me how to make it go away!',
    baseSuspicion: 12,
    gullibility: 88,
    patience: 80,
  },

  // --- COLLEGE STUDENTS & GAMERS (MALE & FEMALE) ---
  {
    name: 'Kyle "NoScope" Henderson',
    gender: 'male',
    archetype: 'Esports Streamer',
    personality: 'Fast-Talking & Chill',
    personalityDescription: 'Listening to techno music, speaks in gamer slang, wants it fixed so he can stream.',
    age: 21,
    voice: 'Zephyr',
    hook: 'Yo support! My stream overlay popped a billing alert for five hundred bucks. Let’s get that refund processed GG.',
    baseSuspicion: 15,
    gullibility: 78,
    patience: 70,
  },
  {
    name: 'Zoe Kravitz-Park',
    gender: 'female',
    archetype: 'Computer Animation Student',
    personality: 'Bright & Tech-Savvy',
    personalityDescription: 'Knows 3D software and GPUs, wants to ensure the license error is wiped from registry.',
    age: 23,
    voice: 'Puck',
    hook: 'Hey, I was rendering a Maya project and got an unauthorized licensing debit notice. Can we clear the merchant authorization?',
    baseSuspicion: 20,
    gullibility: 62,
    patience: 72,
  },
  {
    name: 'Tanner Hayes',
    gender: 'male',
    archetype: 'College Lacrosse Player',
    personality: 'Laid-Back & Trusting',
    personalityDescription: 'Super relaxed, eating cereal while on call, follows directions without question.',
    age: 20,
    voice: 'Zephyr',
    hook: 'Sup dude. My dad’s card got charged for some security software on my laptop. He told me to call and get it refunded.',
    baseSuspicion: 11,
    gullibility: 86,
    patience: 78,
  },
  {
    name: 'Brianna "Bree" Taylor',
    gender: 'female',
    archetype: 'Journalism Major',
    personality: 'Curious & Inquisitive',
    personalityDescription: 'Asks a couple questions, but writes everything down and cooperates nicely.',
    age: 22,
    voice: 'Puck',
    hook: 'Hi! I’m working on a campus paper article and this charge appeared on my banking app. How do we file the dispute?',
    baseSuspicion: 17,
    gullibility: 74,
    patience: 75,
  },

  // --- SENIORS & RETIREES (ADDITIONAL DIVERSE MALE & FEMALE) ---
  {
    name: 'Mortimer "Mort" Snodgrass',
    gender: 'male',
    archetype: 'Retired Bridge Champion',
    personality: 'Patient & Meticulous',
    personalityDescription: 'Writes with a fountain pen, asks the operator to repeat numbers slowly and clearly.',
    age: 81,
    voice: 'Charon',
    hook: 'Good afternoon, sir. My daughter set up this computer for me. A large red banner says my protection expired.',
    baseSuspicion: 11,
    gullibility: 87,
    patience: 92,
  },
  {
    name: 'Agnes Penelope Finch',
    gender: 'female',
    archetype: 'Retired Opera Singer',
    personality: 'Dramatic & Friendly',
    personalityDescription: 'Speaks with theatrical resonance, thrilled that customer service answered so swiftly.',
    age: 77,
    voice: 'Kore',
    hook: 'Aha! At last, human contact! A terrible mechanical screech emanated from my machine warning of an illicit surcharge!',
    baseSuspicion: 10,
    gullibility: 89,
    patience: 90,
  },
  {
    name: 'Homer "Skip" Sullivan',
    gender: 'male',
    archetype: 'Retired Coast Guard Captain',
    personality: 'Authoritative yet Trusting',
    personalityDescription: 'Respects chain of command, ready to follow the technician\'s standard operating procedure.',
    age: 74,
    voice: 'Fenrir',
    hook: 'Ahoy technician. My navigational monitor is displaying an overdue license flag. Standing by for your instructions.',
    baseSuspicion: 13,
    gullibility: 81,
    patience: 86,
  },
  {
    name: 'Mildred "Millie" Crabtree',
    gender: 'female',
    archetype: 'Retired Baker',
    personality: 'Sweet & Maternal',
    personalityDescription: 'Offers to send cookies through the mail to the technician, readily gives credit card numbers.',
    age: 79,
    voice: 'Kore',
    hook: 'Hello darling! Have you eaten lunch today? A silly message popped up demanding four hundred dollars from my card.',
    baseSuspicion: 8,
    gullibility: 93,
    patience: 95,
  },
  {
    name: 'Otis Washington',
    gender: 'male',
    archetype: 'Retired Jazz Saxophonist',
    personality: 'Smooth & Easygoing',
    personalityDescription: 'Cool demeanor, laughs warmly, takes everything in stride.',
    age: 72,
    voice: 'Charon',
    hook: 'Hey now, technician. Got a little out-of-tune charge on my monthly bill. Let’s get this rhythm back on track.',
    baseSuspicion: 12,
    gullibility: 83,
    patience: 88,
  },
  {
    name: 'Bernadette "Bernie" Kowalski',
    gender: 'female',
    archetype: 'Retired Nurse Supervisor',
    personality: 'Orderly & Practical',
    personalityDescription: 'Follows treatment plans easily, very cooperative once guided calmly.',
    age: 68,
    voice: 'Kore',
    hook: 'Hello support. I need to administer a cancellation to this $460 recurring software fee. What is our first step?',
    baseSuspicion: 16,
    gullibility: 76,
    patience: 82,
  },

  // --- TRADESPEOPLE & CRAFTSMEN (MALE & FEMALE) ---
  {
    name: 'Hank "Wrench" MacGowan',
    gender: 'male',
    archetype: 'Heavy Equipment Mechanic',
    personality: 'Blunt & Trusting',
    personalityDescription: 'Values straight shooting, happy to read out codes if you keep it simple.',
    age: 51,
    voice: 'Charon',
    hook: 'Yeah, afternoon. Got a tablet in my truck that’s locked with a security warning. What do I gotta press?',
    baseSuspicion: 16,
    gullibility: 74,
    patience: 72,
  },
  {
    name: 'Lorraine Vance-Kemp',
    gender: 'female',
    archetype: 'Master Plumber',
    personality: 'Practical & Fast',
    personalityDescription: 'Used to unclogging pipes, treats billing problems the same way.',
    age: 49,
    voice: 'Puck',
    hook: 'Hi. I saw a $380 unauthorized charge on my trade account. Let’s flush this charge out right now.',
    baseSuspicion: 18,
    gullibility: 69,
    patience: 70,
  },
  {
    name: 'Guillermo "Memo" Reyes',
    gender: 'male',
    archetype: 'Landscape Architect',
    personality: 'Cheerful & Cooperative',
    personalityDescription: 'Friendly family man, speaks politely and cooperates readily.',
    age: 43,
    voice: 'Zephyr',
    hook: 'Buenas tardes! My office computer showed an invoice that needs to be reversed back to my credit card.',
    baseSuspicion: 14,
    gullibility: 79,
    patience: 80,
  },
  {
    name: 'Dale R. Strickland',
    gender: 'male',
    archetype: 'HVAC Technician',
    personality: 'Straight-Shooter',
    personalityDescription: 'In between service calls, wants quick action, happy to provide verification info.',
    age: 46,
    voice: 'Charon',
    hook: 'Hey man, got a $420 billing notification while driving to a compressor job. Let’s get this reversed ASAP.',
    baseSuspicion: 17,
    gullibility: 72,
    patience: 68,
  },

  // --- BUSINESS EXECUTIVES & MANAGERS (MALE & FEMALE) ---
  {
    name: 'Sterling Vance III',
    gender: 'male',
    archetype: 'Venture Capital Associate',
    personality: 'Fast-Paced & Tech-Fluent',
    personalityDescription: 'Speaks in buzzwords, values speed and streamlined processes.',
    age: 33,
    voice: 'Zephyr',
    hook: 'Hey, I’m seeing an unauthorized ARR line item hit our corporate credit card. Can we execute the clawback protocol?',
    baseSuspicion: 21,
    gullibility: 59,
    patience: 65,
  },
  {
    name: 'Genevieve Dupond',
    gender: 'female',
    archetype: 'Luxury Hotel Concierge',
    personality: 'Polite & Accommodating',
    personalityDescription: 'Always diplomatic and eager to facilitate smooth resolution.',
    age: 40,
    voice: 'Kore',
    hook: 'Good day. A guest billing discrepancy has occurred regarding our reservation terminals. Please guide me through the resolution.',
    baseSuspicion: 16,
    gullibility: 75,
    patience: 82,
  },
  {
    name: 'Kendrick Lamar-Cole',
    gender: 'male',
    archetype: 'Marketing Director',
    personality: 'Upbeat & Professional',
    personalityDescription: 'Communicates clearly, cooperative when treated with enthusiasm.',
    age: 38,
    voice: 'Zephyr',
    hook: 'Hi support team! I noticed an unexpected subscription fee debited from our agency card. Let’s get that refund processed.',
    baseSuspicion: 17,
    gullibility: 71,
    patience: 74,
  },
  {
    name: 'Veronica Stone',
    gender: 'female',
    archetype: 'Talent Acquisition Director',
    personality: 'Energetic & Conversational',
    personalityDescription: 'Loves building rapport, talks easily, very trusting once friendly tone is set.',
    age: 39,
    voice: 'Puck',
    hook: 'Hello! Thanks for picking up so fast. I have an unwanted charge notification here that I’d love to get cleared up.',
    baseSuspicion: 15,
    gullibility: 78,
    patience: 77,
  },

  // --- DIVERSE MORE PERSONALITIES TO SURPASS 100+ (TOTAL 110+ HANDCRAFTED PROFILES) ---
  {
    name: 'Donald "Donnie" Fletcher',
    gender: 'male',
    archetype: 'Bowling Alley Manager',
    personality: 'Good-Humored & Relaxed',
    personalityDescription: 'Background bowling pins sound, laughing and happy to cooperate.',
    age: 56,
    voice: 'Charon',
    hook: 'Hey there! Computer at lane 12 popped an error about anti-virus bills. How do we strike this out?',
    baseSuspicion: 13,
    gullibility: 82,
    patience: 80,
  },
  {
    name: 'Fiona MacTavish',
    gender: 'female',
    archetype: 'Bed & Breakfast Host',
    personality: 'Warm & Cheerful',
    personalityDescription: 'Scottish hospitality, trusts polite representatives completely.',
    age: 60,
    voice: 'Kore',
    hook: 'Hello love! Just serving breakfast to our guests when this invoice pinged me. Can you cancel it for me?',
    baseSuspicion: 10,
    gullibility: 89,
    patience: 88,
  },
  {
    name: 'Jasper "Jaz" Holloway',
    gender: 'male',
    archetype: 'Record Store Owner',
    personality: 'Vinyl Connoisseur & Chill',
    personalityDescription: 'Spinning records in the background, relaxed and trusting.',
    age: 47,
    voice: 'Zephyr',
    hook: 'Hey man, got an alert on the register saying some digital security plan renewed. Let’s drop the needle on a refund.',
    baseSuspicion: 14,
    gullibility: 79,
    patience: 82,
  },
  {
    name: 'Naomi Campbell-Ross',
    gender: 'female',
    archetype: 'Fashion Stylist',
    personality: 'Trendy & Fast-Paced',
    personalityDescription: 'Busy on photo shoots, provides card details to get off phone fast.',
    age: 31,
    voice: 'Puck',
    hook: 'Hi! Quick question, my assistant flagged a charge for $440 that we didn’t approve. Can you credit it back immediately?',
    baseSuspicion: 16,
    gullibility: 73,
    patience: 66,
  },
  {
    name: 'Emilio Santoro',
    gender: 'male',
    archetype: 'Espresso Machine Technician',
    personality: 'Passionate & Friendly',
    personalityDescription: 'Italian accent nuances, talks with hands, cooperative and respectful.',
    age: 43,
    voice: 'Zephyr',
    hook: 'Ciao! I received an email that an automatic debit was made from my account for computer software. Let us fix this!',
    baseSuspicion: 15,
    gullibility: 78,
    patience: 79,
  },
  {
    name: 'Doris Jean Weatherford',
    gender: 'female',
    archetype: 'Retired Bingo Caller',
    personality: 'Loud & Jovial',
    personalityDescription: 'Booms with friendly energy, readily repeats numbers.',
    age: 72,
    voice: 'Kore',
    hook: 'B-4! That’s what popped up on my screen, haha! Seriously though, what do I need to read you to cancel this bill, honey?',
    baseSuspicion: 9,
    gullibility: 91,
    patience: 90,
  },
  {
    name: 'Quentin Albright',
    gender: 'male',
    archetype: 'Museum Registrar',
    personality: 'Meticulous & Calm',
    personalityDescription: 'Appreciates proper cataloging and verification numbers.',
    age: 51,
    voice: 'Fenrir',
    hook: 'Good morning. I am following up on a pending authorization notice against our artifact inventory terminal.',
    baseSuspicion: 20,
    gullibility: 64,
    patience: 78,
  },
  {
    name: 'Marjorie "Marge" Higgins',
    gender: 'female',
    archetype: 'Retired Telephone Switchboard Operator',
    personality: 'Professional & Friendly',
    personalityDescription: 'Knows telecom jargon from 40 years ago, loves chatting with operators.',
    age: 82,
    voice: 'Kore',
    hook: 'Hello operator! It’s wonderful to speak with someone. My monitor screen gave me your number for a billing check.',
    baseSuspicion: 8,
    gullibility: 94,
    patience: 95,
  },
  {
    name: 'Winston Churchill-Vance',
    gender: 'male',
    archetype: 'Bulldog Breeder',
    personality: 'Gruff & Good-Natured',
    personalityDescription: 'Barking dogs in background, chuckles easily, cooperates gladly.',
    age: 65,
    voice: 'Charon',
    hook: 'Afternoon! The pups are making a racket, but I got a notice about a computer charge that needs cancelling.',
    baseSuspicion: 13,
    gullibility: 83,
    patience: 84,
  },
  {
    name: 'Sylvia Plath-Kowalski',
    gender: 'female',
    archetype: 'Poetry Workshop Leader',
    personality: 'Reflective & Gentle',
    personalityDescription: 'Soft-spoken, takes guidance gracefully, very cooperative.',
    age: 59,
    voice: 'Kore',
    hook: 'Hello. An alert appeared across my screen like an unexpected storm. I would be grateful for your assistance in dispersing it.',
    baseSuspicion: 12,
    gullibility: 84,
    patience: 86,
  },
  {
    name: 'Kirkland "Kirk" Douglas-Cole',
    gender: 'male',
    archetype: 'Community Theater Director',
    personality: 'Dramatic & Friendly',
    personalityDescription: 'Speaks with flourish, treats the phone call like a dramatic scene, cooperates enthusiastically.',
    age: 57,
    voice: 'Fenrir',
    hook: 'Greetings from stage left! A phantom fee of $390 has struck our production account! Guide me to our triumphant refund!',
    baseSuspicion: 14,
    gullibility: 81,
    patience: 82,
  },
  {
    name: 'Penny Lane-O\'Connor',
    gender: 'female',
    archetype: 'Record Collector & Barista',
    personality: 'Sweet & Breezy',
    personalityDescription: 'Upbeat and friendly, happily types codes or reads card numbers.',
    age: 25,
    voice: 'Puck',
    hook: 'Hey! I was steaming oat milk when I saw a notification for a software charge. How can we cancel it?',
    baseSuspicion: 12,
    gullibility: 85,
    patience: 80,
  },
  {
    name: 'Grover Cleveland-Hayes',
    gender: 'male',
    archetype: 'Retired Hardware Store Clerk',
    personality: 'Handy & Practical',
    personalityDescription: 'Used to helping customers find the right bolt, very helpful and compliant.',
    age: 76,
    voice: 'Charon',
    hook: 'Hello young fellow. Got a computer bill here I don’t recognize. Tell me what tool we need to fix it.',
    baseSuspicion: 11,
    gullibility: 88,
    patience: 88,
  },
  {
    name: 'Tallulah Bankhead-Smith',
    gender: 'female',
    archetype: 'Retired Southern Belle',
    personality: 'Charming & Flirtatious',
    personalityDescription: 'Loves charming the operator, cooperative and generous with details.',
    age: 70,
    voice: 'Kore',
    hook: 'Well hello there handsome. My computer screen is flashing red and told me to call this darling number right away.',
    baseSuspicion: 9,
    gullibility: 92,
    patience: 90,
  },
  {
    name: 'Lyle "Clyde" Barrow',
    gender: 'male',
    archetype: 'Vintage Car Restorer',
    personality: 'Observant & Calm',
    personalityDescription: 'Calm under the hood, listens to the engine sound of your explanation.',
    age: 53,
    voice: 'Fenrir',
    hook: 'Howdy. My invoice terminal shows an overdue charge on our diagnostic software. What’s our rollback protocol?',
    baseSuspicion: 18,
    gullibility: 70,
    patience: 74,
  },
  {
    name: 'Glenda "Goody" Proctor',
    gender: 'female',
    archetype: 'Herbal Tea Apothecary Owner',
    personality: 'Peaceful & Trusting',
    personalityDescription: 'Calm and zen, easily guided by gentle reassurances.',
    age: 52,
    voice: 'Kore',
    hook: 'Greetings of peace. An alarm on my device indicated a financial disruption of $420. How shall we restore balance?',
    baseSuspicion: 11,
    gullibility: 87,
    patience: 88,
  },
  {
    name: 'Seamus O\'Reilly',
    gender: 'male',
    archetype: 'Irish Pub Landlord',
    personality: 'Jovial & Boisterous',
    personalityDescription: 'Clinking glasses in background, friendly banter, ready to clear the invoice.',
    age: 59,
    voice: 'Fenrir',
    hook: 'Top of the morning! I’ve got an alert on the register here saying we’ve been charged for an internet shield. Let’s get it back in the till!',
    baseSuspicion: 14,
    gullibility: 81,
    patience: 82,
  },
  {
    name: 'Ingrid Bergman-Larsson',
    gender: 'female',
    archetype: 'Scandinavian Furniture Designer',
    personality: 'Minimalist & Direct',
    personalityDescription: 'Values clean steps and efficiency, cooperates easily.',
    age: 45,
    voice: 'Kore',
    hook: 'Hello. I have received an automated debit receipt for software we do not utilize. Please reverse this transaction.',
    baseSuspicion: 17,
    gullibility: 68,
    patience: 75,
  },
  {
    name: 'Baxter "Bax" Stockman',
    gender: 'male',
    archetype: 'Amateur Drone Enthusiast',
    personality: 'Tech-Curious & Friendly',
    personalityDescription: 'Understands basic firmware and Wi-Fi, enjoys troubleshooting alongside the operator.',
    age: 36,
    voice: 'Zephyr',
    hook: 'Hey tech team! My telemetry screen flashed an IP conflict and an anti-virus invoice. Let’s debug this together.',
    baseSuspicion: 19,
    gullibility: 65,
    patience: 76,
  },
  {
    name: 'Consuelo Martinez',
    gender: 'female',
    archetype: 'Community Center Director',
    personality: 'Warm & Caring',
    personalityDescription: 'Takes care of everyone, very respectful of support workers, highly cooperative.',
    age: 58,
    voice: 'Puck',
    hook: 'Hello dear! Thank you for picking up. I have the invoice right here on my desk. Please guide me through it.',
    baseSuspicion: 12,
    gullibility: 86,
    patience: 86,
  },
  {
    name: 'Alfie "Al" Hopkins',
    gender: 'male',
    archetype: 'Fish & Chips Shop Owner',
    personality: 'Cheerful & Chatty',
    personalityDescription: 'Sizzling fryer background, talks fast and friendly, follows directions readily.',
    age: 50,
    voice: 'Charon',
    hook: 'Right, cheers mate! My front till showed a banner saying four hundred quid came off the card. What do we do to get it refunded?',
    baseSuspicion: 15,
    gullibility: 79,
    patience: 76,
  },
  {
    name: 'Ursula K. Vance',
    gender: 'female',
    archetype: 'Science Fiction Archivist',
    personality: 'Scholarly & Inquisitive',
    personalityDescription: 'Values documentation and transaction receipts.',
    age: 61,
    voice: 'Kore',
    hook: 'Greetings. An unrecognized recurring data charge has penetrated my workstation ledger. How do we initiate the cancel sequence?',
    baseSuspicion: 18,
    gullibility: 66,
    patience: 80,
  },
  {
    name: 'Cyrus "Cy" Vance-Pond',
    gender: 'male',
    archetype: 'Lighthouse Keeper',
    personality: 'Solitary & Patient',
    personalityDescription: 'Calm ocean sounds, slow and measured speaking style, very patient.',
    age: 64,
    voice: 'Fenrir',
    hook: 'Hello out there. The maritime relay terminal gave a warning about an expired firewall subscription. What is the procedure?',
    baseSuspicion: 12,
    gullibility: 82,
    patience: 92,
  },
  {
    name: 'Prudence "Prue" Goodall',
    gender: 'female',
    archetype: 'Village Postmistress',
    personality: 'Orderly & Sweet',
    personalityDescription: 'Comfortable with government forms and receipts, happy to read out digits.',
    age: 69,
    voice: 'Kore',
    hook: 'Good day. A red stamped alert appeared on my postal computer. I have my ledger ready to record your instructions.',
    baseSuspicion: 11,
    gullibility: 87,
    patience: 89,
  },
  {
    name: 'Buster "Buzzer" Brown',
    gender: 'male',
    archetype: 'Vintage Arcade Repairman',
    personality: 'Mechanically Minded & Friendly',
    personalityDescription: 'Fascinated by circuit boards, eager to follow technical instructions.',
    age: 52,
    voice: 'Charon',
    hook: 'Hey support! My pinball counter machine showed an error code with this phone number. What test sequence should I run?',
    baseSuspicion: 16,
    gullibility: 75,
    patience: 80,
  },
  {
    name: 'Serena Joy-Montague',
    gender: 'female',
    archetype: 'Ballet Academy Registrar',
    personality: 'Graceful & Cooperative',
    personalityDescription: 'Speaks with melodious cadence, very polite and compliant.',
    age: 44,
    voice: 'Puck',
    hook: 'Good morning. Our dance studio terminal showed an erroneous charge for security software. How may I assist in reversing it?',
    baseSuspicion: 14,
    gullibility: 81,
    patience: 84,
  },
  {
    name: 'Desmond "Des" Tutu-Smith',
    gender: 'male',
    archetype: 'Community Mediation Officer',
    personality: 'Peace-Loving & Receptive',
    personalityDescription: 'Values harmony, avoids conflict, cooperates with warmth.',
    age: 60,
    voice: 'Zephyr',
    hook: 'Greetings friend. A small misunderstanding in billing seems to have occurred on my device. Let us work together to resolve it.',
    baseSuspicion: 11,
    gullibility: 86,
    patience: 90,
  },
  {
    name: 'Wilhelmina "Willa" Cather-Lee',
    gender: 'female',
    archetype: 'Landscape Painter',
    personality: 'Artistic & Dreamy',
    personalityDescription: 'Thinks in colors, very open and trusting of friendly guidance.',
    age: 56,
    voice: 'Kore',
    hook: 'Hello! I was painting outdoors on my tablet and a red notification appeared. Tell me what colors and numbers to tap!',
    baseSuspicion: 9,
    gullibility: 90,
    patience: 88,
  },
  {
    name: 'Orson "Welles" Sterling',
    gender: 'male',
    archetype: 'Voiceover Artist',
    personality: 'Resonant & Friendly',
    personalityDescription: 'Deep, rich radio voice, loves conversational back-and-forth.',
    age: 54,
    voice: 'Fenrir',
    hook: 'Good evening. This is Orson Sterling. An unexpected fee of $480 has been charged to my studio account. Let us proceed with the reversal.',
    baseSuspicion: 16,
    gullibility: 72,
    patience: 82,
  },
  {
    name: 'Rowena Raven-Scott',
    gender: 'female',
    archetype: 'Falconer & Bird Sanctuary Host',
    personality: 'Patient & Observant',
    personalityDescription: 'Calm and steady, very respectful and accommodating.',
    age: 48,
    voice: 'Puck',
    hook: 'Hello there. The sanctuary computer gave an alert about our predator radar software. How do we cancel this renewal fee?',
    baseSuspicion: 15,
    gullibility: 77,
    patience: 84,
  },
  {
    name: 'Phineas "Fin" Gage',
    gender: 'male',
    archetype: 'Model Railroad Hobbyist',
    personality: 'Detail-Oriented & Patient',
    personalityDescription: 'Takes his time, loves organized procedures.',
    age: 67,
    voice: 'Charon',
    hook: 'Afternoon. My train controller display threw up a communication error and a debit invoice. Guide me down the right track.',
    baseSuspicion: 12,
    gullibility: 83,
    patience: 89,
  },
  {
    name: 'Constance "Connie" Truelove',
    gender: 'female',
    archetype: 'Bridal Gown Tailor',
    personality: 'Attentive & Gentle',
    personalityDescription: 'Very cooperative, listens carefully to instructions.',
    age: 63,
    voice: 'Kore',
    hook: 'Hello sweetheart! I have my measuring tape around my neck and my card right here. What numbers do you need me to read?',
    baseSuspicion: 10,
    gullibility: 90,
    patience: 91,
  },
  {
    name: 'Zephaniah "Zeph" Miller',
    gender: 'male',
    archetype: 'Grain Silo Operator',
    personality: 'Down-to-Earth & Honest',
    personalityDescription: 'Hardworking rural worker, trusts honest-sounding support reps.',
    age: 58,
    voice: 'Charon',
    hook: 'Hey support. The farm terminal gave a beep saying $450 was charged for cloud security. How do we get that refunded back?',
    baseSuspicion: 14,
    gullibility: 80,
    patience: 82,
  },
  {
    name: 'Evangeline "Eva" Vance-Delacroix',
    gender: 'female',
    archetype: 'French Pastry Chef',
    personality: 'Passionate & Lively',
    personalityDescription: 'Warm, expressive, cooperative when treated with courtesy.',
    age: 41,
    voice: 'Puck',
    hook: 'Bonjour! I have an unexpected charge notification on my kitchen tablet. Please help me cancel this so I can return to my croissants!',
    baseSuspicion: 13,
    gullibility: 82,
    patience: 78,
  },
  {
    name: 'Balthazar "Baz" King',
    gender: 'male',
    archetype: 'Antique Jewelry Appraiser',
    personality: 'Polite & Discerning',
    personalityDescription: 'Examines details with care, calmed by authoritative professionalism.',
    age: 62,
    voice: 'Fenrir',
    hook: 'Good day. My inventory computer has displayed a notification regarding an unauthorized software renewal. What is our recourse?',
    baseSuspicion: 19,
    gullibility: 65,
    patience: 80,
  },
  {
    name: 'Tobias "Toby" Flenderson-Vance',
    gender: 'male',
    archetype: 'HR Specialist',
    personality: 'Soft-Spoken & Mild',
    personalityDescription: 'Values conflict resolution and calm procedure.',
    age: 46,
    voice: 'Zephyr',
    hook: 'Hi... I received a notification about an unauthorized charge on my account. I was hoping you could help me file a cancellation request.',
    baseSuspicion: 14,
    gullibility: 81,
    patience: 88,
  },
  {
    name: 'Helena Bonham-Carter-Scott',
    gender: 'female',
    archetype: 'Vintage Milliner (Hat Maker)',
    personality: 'Artistic & Quirky',
    personalityDescription: 'Loves patterns, talks about ribbons, very cooperative.',
    age: 55,
    voice: 'Kore',
    hook: 'Hello darling! A crimson banner appeared across my screen while I was shaping a fedora. Can you make it vanish?',
    baseSuspicion: 11,
    gullibility: 86,
    patience: 84,
  },
  {
    name: 'Thaddeus "Thad" Beaumont',
    gender: 'male',
    archetype: 'Genealogist',
    personality: 'Historical & Inquisitive',
    personalityDescription: 'Enjoys family tree records and verification codes.',
    age: 64,
    voice: 'Fenrir',
    hook: 'Good day. While researching 19th-century census data, this pop-up asserted that my security license expired. Let us address this.',
    baseSuspicion: 16,
    gullibility: 72,
    patience: 82,
  },
  {
    name: 'Winifred "Winnie" Sanderson-Cole',
    gender: 'female',
    archetype: 'Herbal Soap Artisan',
    personality: 'Warm & Fragrant',
    personalityDescription: 'Cheerful, loves chatting, follows directions step by step.',
    age: 58,
    voice: 'Kore',
    hook: 'Hello! I was just wrapping lavender soaps when my computer began chiming. What should I do next, dear?',
    baseSuspicion: 10,
    gullibility: 88,
    patience: 89,
  },
  {
    name: 'Clarence "Clancy" Darrow',
    gender: 'male',
    archetype: 'Retired Small-Town Mayor',
    personality: 'Civic-Minded & Friendly',
    personalityDescription: 'Used to resolving citizen disputes, very polite and trusting.',
    age: 73,
    voice: 'Charon',
    hook: 'Well hello there! Clancy here. Looks like the town computer system logged an extra charge on my card. Can we clear this up?',
    baseSuspicion: 12,
    gullibility: 84,
    patience: 87,
  },
  {
    name: 'Leona Helmsley-Jones',
    gender: 'female',
    archetype: 'Bed & Breakfast Owner',
    personality: 'Orderly & Demanding',
    personalityDescription: 'Expects fast service, provides details once assured it is urgent.',
    age: 61,
    voice: 'Puck',
    hook: 'Yes, operator. A $480 invoice appeared on our front lobby desk. I want this cancelled immediately.',
    baseSuspicion: 20,
    gullibility: 65,
    patience: 68,
  },
  {
    name: 'Atticus Finch-Ward',
    gender: 'male',
    archetype: 'Country Defense Attorney',
    personality: 'Fair & Methodical',
    personalityDescription: 'Speaks with southern eloquence, appreciates transparent explanations.',
    age: 57,
    voice: 'Fenrir',
    hook: 'Good afternoon. I am reviewing an unexpected debit notice that appeared upon my office terminal. I trust we can rectify this amicably.',
    baseSuspicion: 22,
    gullibility: 56,
    patience: 80,
  },
  {
    name: 'Daisy Buchanan-Lee',
    gender: 'female',
    archetype: 'Socialite & Philanthropist',
    personality: 'Charming & Breezy',
    personalityDescription: 'Takes everything lightly, happy to have someone else handle computer trouble.',
    age: 38,
    voice: 'Puck',
    hook: 'Oh hello! The screen is doing something dreadfully strange and says hundreds of dollars are pending. Could you just fix it, please?',
    baseSuspicion: 11,
    gullibility: 88,
    patience: 85,
  },
  {
    name: 'Seaborn "Sea" Vance',
    gender: 'male',
    archetype: 'Lobster Boat Captain',
    personality: 'Gruff & Salt-of-the-Earth',
    personalityDescription: 'Speaks with coastal Maine cadence, trusts straightforward folks.',
    age: 62,
    voice: 'Charon',
    hook: 'Ahoy. Got a warning message on the marina laptop about an overdue software charge. Tell me what to punch in so I can get back to the docks.',
    baseSuspicion: 15,
    gullibility: 78,
    patience: 75,
  },
  {
    name: 'Griselda "Zelda" March',
    gender: 'female',
    archetype: 'Stained Glass Artisan',
    personality: 'Creative & Patient',
    personalityDescription: 'Very cooperative and appreciative of technical guidance.',
    age: 59,
    voice: 'Kore',
    hook: 'Hello young man. I was soldering glass when this warning chime sounded. I have my papers right here.',
    baseSuspicion: 10,
    gullibility: 87,
    patience: 88,
  },
  {
    name: 'Benton "Benny" Frazier',
    gender: 'male',
    archetype: 'Barbershop Quartet Singer',
    personality: 'Melodious & Cheerful',
    personalityDescription: 'Hums between sentences, very friendly and easy to persuade.',
    age: 66,
    voice: 'Zephyr',
    hook: 'Hello hello hello! A discordant note sounded from my computer speaker about an unauthorized charge. Help me harmonize this refund!',
    baseSuspicion: 11,
    gullibility: 86,
    patience: 86,
  },
  {
    name: 'Lavinia "Vinnie" Fontaine',
    gender: 'female',
    archetype: 'French Perfumer',
    personality: 'Refined & Sensual',
    personalityDescription: 'Speaks with chic elegance, cooperative when treated with luxury customer service tone.',
    age: 42,
    voice: 'Puck',
    hook: 'Bonjour support! An unexpected scent of financial trouble appeared on my boutique ledger. Let us eliminate this charge.',
    baseSuspicion: 14,
    gullibility: 80,
    patience: 82,
  },
  {
    name: 'Ignatius J. Reilly-Cole',
    gender: 'male',
    archetype: 'Eccentric Philosopher',
    personality: 'Grandiloquent & Dramatic',
    personalityDescription: 'Complains about the modern world, easily calmed down by being called a valued scholar.',
    age: 40,
    voice: 'Charon',
    hook: 'Good heavens! My delicate valve has been agitated by a fraudulent computational assessment of $490! Restore my tranquility at once!',
    baseSuspicion: 18,
    gullibility: 68,
    patience: 70,
  },
  {
    name: 'Nora Charles-Sterling',
    gender: 'female',
    archetype: 'Mystery Book Club Host',
    personality: 'Witty & Playful',
    personalityDescription: 'Enjoys sleuthing, cooperates when presented with "detective evidence" of the refund.',
    age: 45,
    voice: 'Puck',
    hook: 'Well, well. It seems we have a mystery transaction of $430 afoot. Are you the detective assigned to solve it?',
    baseSuspicion: 17,
    gullibility: 72,
    patience: 78,
  },
  {
    name: 'Montgomery "Monty" Burns-Ward',
    gender: 'male',
    archetype: 'Retired Railroad Magnate Heir',
    personality: 'Old-School & Formal',
    personalityDescription: 'Expects crisp customer service and readily authorizes payments when assured of protocol.',
    age: 79,
    voice: 'Fenrir',
    hook: 'Ah, greetings operator. My telegraphic terminal—er, monitor—indicated a disputed recurring voucher. Excellent. Proceed with the cancellation.',
    baseSuspicion: 16,
    gullibility: 75,
    patience: 84,
  },
  {
    name: 'Flora Post-Vance',
    gender: 'female',
    archetype: 'Practical Rural Organizer',
    personality: 'Sensible & Cheerful',
    personalityDescription: 'Values good organization and tidy accounts, cooperates swiftly.',
    age: 36,
    voice: 'Puck',
    hook: 'Good morning! Everything on the farm should be tidy and shipshape, and this $410 error is certainly not tidy. Let’s tidy it up!',
    baseSuspicion: 13,
    gullibility: 81,
    patience: 82,
  },
  {
    name: 'Linus "Blanket" Van Pelt',
    gender: 'male',
    archetype: 'Philosophical Bookstore Clerk',
    personality: 'Gentle & Reflective',
    personalityDescription: 'Calm, loves books, never raises his voice.',
    age: 31,
    voice: 'Zephyr',
    hook: 'Hello. There’s a quiet reminder on my computer that four hundred dollars was billed in error. I’d appreciate your help setting it right.',
    baseSuspicion: 12,
    gullibility: 85,
    patience: 86,
  },
  {
    name: 'Bettina "Betty" Boop-Miller',
    gender: 'female',
    archetype: 'Vintage Diner Waitress',
    personality: 'Peppy & Energetic',
    personalityDescription: 'Calling between pouring coffee refills, talks with sweet energy.',
    age: 49,
    voice: 'Puck',
    hook: 'Hey hon! How’s your shift going? A little ticket popped out of our register saying to call support for a refund. What’s the special today?',
    baseSuspicion: 11,
    gullibility: 87,
    patience: 85,
  },
  {
    name: 'Sherlock "Lock" Vance',
    gender: 'male',
    archetype: 'Private Investigator',
    personality: 'Observant & Analytical',
    personalityDescription: 'Observes tone and pauses, but values hard reference numbers.',
    age: 47,
    voice: 'Fenrir',
    hook: 'Evening. I received an automated trace on a pending credit transaction. What’s the authorization code on your terminal?',
    baseSuspicion: 24,
    gullibility: 52,
    patience: 74,
  },
  {
    name: 'Wilma Flintstone-Smith',
    gender: 'female',
    archetype: 'Geology Professor',
    personality: 'Solid & Grounded',
    personalityDescription: 'Appreciates factual explanations, cooperates once reasons are stated clearly.',
    age: 53,
    voice: 'Kore',
    hook: 'Hello technician. My campus laptop popped a basalt-heavy red alert about an expired license. Let us carve out a solution.',
    baseSuspicion: 17,
    gullibility: 70,
    patience: 80,
  },
  {
    name: 'Giles Corey-Hayes',
    gender: 'male',
    archetype: 'Cider Mill Operator',
    personality: 'Sturdy & Patient',
    personalityDescription: 'Patient as pressing apples, speaks with deep rumbling tone.',
    age: 63,
    voice: 'Charon',
    hook: 'Afternoon to ye. Got an alert on the mill’s scales computer saying a card was charged. Let’s press out the details.',
    baseSuspicion: 14,
    gullibility: 80,
    patience: 85,
  },
  {
    name: 'Pollyanna Whittier-Jones',
    gender: 'female',
    archetype: 'Optimism Coach',
    personality: 'Unstoppably Cheerful',
    personalityDescription: 'Finds the bright side in everything, completely trusting.',
    age: 34,
    voice: 'Puck',
    hook: 'Hello! Isn’t it wonderful that we have computers that connect us together? Even if there is an accidental charge, I know we can fix it!',
    baseSuspicion: 7,
    gullibility: 96,
    patience: 95,
  },
  {
    name: 'Cosmo Kramer-Bell',
    gender: 'male',
    archetype: 'Eccentric Inventor',
    personality: 'Manic & Excitable',
    personalityDescription: 'Speaks fast with wild hand gestures, loves high-tech jargon.',
    age: 48,
    voice: 'Zephyr',
    hook: 'Giddyup! The screen, it’s flashing red, support! It says my sub-processor needs an authorized cancellation token! What’s the play?!',
    baseSuspicion: 13,
    gullibility: 85,
    patience: 72,
  },
  {
    name: 'Elaine Benes-Ward',
    gender: 'female',
    archetype: 'Manuscript Editor',
    personality: 'Sarcastic & Busy',
    personalityDescription: 'Taps her pen, wants things done properly and quickly.',
    age: 41,
    voice: 'Puck',
    hook: 'Yeah, hi. I’m editing an eight-hundred-page manuscript and this ridiculous pop-up is blocking my margins. How do I get rid of it?',
    baseSuspicion: 19,
    gullibility: 65,
    patience: 64,
  },
  {
    name: 'George Costanza-Vance',
    gender: 'male',
    archetype: 'Anxious Assistant to the Traveling Secretary',
    personality: 'Neurotic & Worried',
    personalityDescription: 'Freaks out about losing money, easily calmed down by being told he is completely protected.',
    age: 44,
    voice: 'Charon',
    hook: 'Listen to me, I can’t lose four hundred dollars! My boss will find out! Is this guaranteed? Are you positive this refund goes through?!',
    baseSuspicion: 17,
    gullibility: 82,
    patience: 65,
  },
  {
    name: 'Morty Seinfeld-Finch',
    gender: 'male',
    archetype: 'Retired Raincoat Salesman',
    personality: 'Opinionated & Gullible',
    personalityDescription: 'Complains about modern gizmos, but readily follows instructions.',
    age: 78,
    voice: 'Fenrir',
    hook: 'Hello? Who’s this? Some gadget in the condominium clubhouse told me to dial this number. My wife says our card was charged!',
    baseSuspicion: 14,
    gullibility: 85,
    patience: 82,
  },
  {
    name: 'Helen Seinfeld-Finch',
    gender: 'female',
    archetype: 'Protective Mother & Retiree',
    personality: 'Warm & Concerned',
    personalityDescription: 'Wants to protect her family’s checking balance, very sweet to the operator.',
    age: 75,
    voice: 'Kore',
    hook: 'Hello sweetheart. Morty is getting worked up, so I took the receiver. Can you help us take this charge off our account, dear?',
    baseSuspicion: 9,
    gullibility: 91,
    patience: 92,
  },
  {
    name: 'Frank Costanza-Frazier',
    gender: 'male',
    archetype: 'Retired Cook & Veteran',
    personality: 'Loud & Demanding',
    personalityDescription: 'Shouts on the phone, but obeys simple direct commands.',
    age: 80,
    voice: 'Charon',
    hook: 'SERENITY NOW! Why is there a charge for $450 on my credit card?! You got three minutes to reverse it before I call my credit union!',
    baseSuspicion: 18,
    gullibility: 78,
    patience: 68,
  },
  {
    name: 'Estelle Costanza-Frazier',
    gender: 'female',
    archetype: 'Dramatic Matriarch',
    personality: 'Emotional & Trusting',
    personalityDescription: 'Very expressive, grateful when the operator speaks calmly and kindly.',
    age: 76,
    voice: 'Kore',
    hook: 'Oh God, Frank is screaming! Please technician, you sound like a lovely young person, tell me how we can cancel this before he has a fit!',
    baseSuspicion: 10,
    gullibility: 89,
    patience: 88,
  },
  {
    name: 'Newman "Mailman" Knight',
    gender: 'male',
    archetype: 'Postal Worker & Connoisseur',
    personality: 'Scheming & Flamboyant',
    personalityDescription: 'Loves feeling important, falls for compliments about his intelligence.',
    age: 48,
    voice: 'Fenrir',
    hook: 'Hello support... When you control the mail, you control information, but this debit from my credit card eludes even me. Explain yourself!',
    baseSuspicion: 21,
    gullibility: 68,
    patience: 72,
  },
  {
    name: 'Peterman "J." Sterling',
    gender: 'male',
    archetype: 'Global Catalog Adventurer',
    personality: 'Poetic & Adventurous',
    personalityDescription: 'Describes the phone call like a trek through Burmese jungles, utterly trusting.',
    age: 58,
    voice: 'Fenrir',
    hook: 'Ah, the rain in Rangoon! It falls with the same persistence as this recurring subscription on my expedition account. Shall we journey to a refund?',
    baseSuspicion: 12,
    gullibility: 85,
    patience: 86,
  },
  {
    name: 'Babu Bhatt-Sharma',
    gender: 'male',
    archetype: 'Dreamer Restaurateur',
    personality: 'Earnest & Trusting',
    personalityDescription: 'Very good person, trusting and polite to everyone.',
    age: 46,
    voice: 'Zephyr',
    hook: 'Hello my friend! I am very good customer, I always pay my bills, but this charge was not made by me! Please help Babu!',
    baseSuspicion: 11,
    gullibility: 89,
    patience: 85,
  },
  {
    name: 'Kenny Bania-Cross',
    gender: 'male',
    archetype: 'Junior Stand-Up Comedian',
    personality: 'Overly Eager & Simple',
    personalityDescription: 'Thinks everything is the best, offers soup to the operator, extremely gullible.',
    age: 35,
    voice: 'Zephyr',
    hook: 'Hey! Did you hear about that charge? It’s gold, support! Gold! But wait, I actually need that money back for Ovaltine. Can you cancel it?',
    baseSuspicion: 8,
    gullibility: 95,
    patience: 84,
  },
  {
    name: 'David Puddy-Vance',
    gender: 'male',
    archetype: 'Automotive Transmission Specialist',
    personality: 'Deadpan & Direct',
    personalityDescription: 'Stares into space, speaks in short monotone sentences, cooperates without objection.',
    age: 42,
    voice: 'Charon',
    hook: 'Yeah, that’s right. Got an alert. High-five. Let’s do the refund thing.',
    baseSuspicion: 10,
    gullibility: 88,
    patience: 90,
  }
];

export function getRandomPersonality(): PersonalityDefinition {
  const idx = Math.floor(Math.random() * PERSONALITIES_DATABASE.length);
  return PERSONALITIES_DATABASE[idx];
}

